#!/usr/bin/env bash
# see https://certsimple.com/blog/nginx-brotli
# Compresses files with brotli

OLDIFS=$IFS
IFS=$'\n'
for FILE in $(find . -type f -iname '*.css' -o -iname '*.js' -o -iname '*.svg' -o -iname '*.json'); do
    echo -n "Compressing ${FILE}..."
    brotli --input ${FILE} --force --output ${FILE}.br;
    chmod 644 ${FILE}.br;
    echo "done."
done
IFS=$OLDIFS
